apiVersion: skaffold/v2beta29
kind: Config
deploy:
  helm:
    releases:
    - name: kafka
      namespace: scheduler
      createNamespace: true
      remoteChart: kafka
      repo: https://ryazanovalexander.github.io/pipeline-manager.charts
      version: 18.0.3
      setValueTemplates:
        persistence:
          enabled: false
        zookeeper:
          persistence:
            enabled: false