apiVersion: skaffold/v2beta29
kind: Config
deploy:
  helm:
    releases:
    - name: kafka
      namespace: scheduler
      createNamespace: true
      chartPath: .dependencies/infrastructure/kafka
      setValueTemplates:
        persistence:
          size: 1Gi
        logPersistence:
          size: 1Gi