apiVersion: skaffold/v2beta29
kind: Config
deploy:
  helm:
    hooks:
      before:
        - host:
            command: ["sh", "-c", "helm repo add bitnami https://charts.bitnami.com/bitnami"]
            os: [darwin, linux]
    releases:
    - name: kafka
      namespace: scheduler
      createNamespace: true
      chartPath: .dependencies/infrastructure/kafka
      setValueTemplates:
        persistence:
          enabled: false
        zookeeper:
          persistence:
            enabled: false