name: Build and test source code

on:
  pull_request:
    branches: [ "main" ]

jobs:       
  build-test:
    runs-on: ubuntu-22.04
    container: docker.io/aryazanov/workload-scheduler-ci-container:0.1
    environment: development
    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow

    - name: Set env
      run: echo "LAST_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

    - name: Build and push CI container
      run: |
        just build-push-ci-container \
          --set LASTTAG ${{ env.LAST_TAG }} \
          ${{ secrets.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_PASSWORD }}

    # - name: Build source code
    #   run: |
    #     just build

    # - name: Run unit tests
    #   run: |
    #     just test

    # - name: Deploying a service and its dependencies on a Minikube cluster
    #   run: |
    #     just minikube-deploy

    # - name: Running integration tests inside a Minikube cluster
    #   run: |
    #     just minikube-test

    # - name: Removing a service and its dependencies from a Minikube cluster
    #   run: |
    #     just minikube-delete