name: Pipeline launched when a pull request is created

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:       
  build-publish:
    runs-on: ubuntu-22.04
    container: docker.io/aryazanov/workload-scheduler-ci-container:0.1
    environment: development
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        skaffold version