name: Build and test source code

on:
  pull_request:
    branches: [ "main" ]

jobs:       
  build-publish:
    runs-on: ubuntu-22.04
    container: docker.io/aryazanov/workload-scheduler-ci-container:0.1
    environment: development
    steps:
    - uses: actions/checkout@v2

    - name: Build source code
      run: |
        just build

    - name: Run unit tests
      run: |
        just test

    - name: Deploying a service and its dependencies on a Minikube cluster
      run: |
        just minikube-deploy

    - name: Running integration tests inside a Minikube cluster
      run: |
        just minikube-test

    - name: Removing a service and its dependencies from a Minikube cluster
      run: |
        just minikube-delete