name: Build and test source code

on:
  pull_request:
    branches: [ "main" ]

jobs:       
  build-test:
    runs-on: self-hosted
    container:
      image: docker.io/aryazanov/workload-scheduler-ci-container:0.1
    environment: development
    steps:
    - uses: actions/checkout@v2

    - name: TMP1
      run: |
        just init

    - name: Build source code
      run: |
        just build

    - name: Run unit tests
      run: |
        just test

    - name: TMP2
      run: |
        just minikube-deploy

    - name: TMP3
      run: |
        just minikube-test