name: Rebuild CI Container

on:
  push:
    branches: [ "main" ]

jobs:       
  build-publish:
    runs-on: ubuntu-22.04
    container: docker.io/aryazanov/workload-scheduler-ci-container:0.1
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        skaffold version

    #  - name: Login to GitHub Container Registry
    #     uses: docker/login-action@v1 
    #     with:
    #       registry: ghcr.io
    #       username: ${{ github.repository_owner }}
    #       password: ${{ secrets.GITHUB_TOKEN }}

    #   - name: Build and run dev container task
    #     uses: stuartleeks/devcontainer-build-run@v0.1
    #     with:
    #       # Change this to point to your image name
    #       imageName: ghcr.io/example/example-devcontainer
    #       # Change this to be your CI task/script
    #       runCmd: make ci-build

      
    #     make build
    # - name: Test
    #   run: |
    #     make test
    # - uses: actions/checkout@v2
    # - run: git fetch --prune --unshallow

    # - name: Set env
    #   run: echo "RELEASE_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

    # - name: Login to DockerHub Registry
    #   run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    # - name: Container
    #   run: |
    #     make container DTAG=${{ env.RELEASE_TAG }}