name: Rebuild CI Container

on:
  push:
    branches: [ "main" ]
  pull_request: # temp
    branches: [ "main" ]

jobs:       
  build-publish:
    runs-on: ubuntu-22.04
    container: docker.io/aryazanov/workload-scheduler-ci-container:0.1
    environment: development
    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow

    - name: Set env
      run: echo "LAST_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

    - name: Build and push Dev container
      run: |
        just build-push-dev-container LASTTAG=${{ env.LAST_TAG }} \
          ${{ secrets.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_PASSWORD }}
