name: Publish artifacts

on:
  push:
    branches:
      - 'releases/**'

jobs:       
  archive-build-artifacts:
    runs-on: self-hosted
    environment: development
    container: docker.io/aryazanov/workload-scheduler-ci-container:0.1
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        just build
    - name: Test
      run: |
        just test
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow

    - name: Set env
      run: echo "RELEASE_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Container
      run: |
        just build-push-image DTAG=${{ env.RELEASE_TAG }}
